#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
KISSBASH_PATH="${DIR%%/test/*}/kissbash"

. "$KISSBASH_PATH/test-util/expecting"

test_explicitly_good() {
    expect_exit_code 0 "
        line_nr=\$(
            . $KISSBASH_PATH/exec/explicitly
            explicitly echo foo 0 1 2>&1 | grep foo | wc -l | sed -e 's/^[[:space:]]*//'
        )
        echo \"there should have 2 lines matching foo, one from stderr and the other stdout\"
        echo \"saw \$line_nr lines\"
        if test \"x\$line_nr\" != \"x2\"; then
            echo \"expecting 2; got \$line_nr\"
            exit 222
        fi
    "
}
