#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
KISSBASH_DIR="${DIR%%/kissbash*}/kissbash/s"

expect_exit_code() {
    expected_retval=$1
    shift

    echo -en "\033[37m[${BASH_SOURCE[0]#*kissbash/}] \033[33m" >&2
    echo "bash -c \"$*\"" >&2
    echo -e "\033[0m" >&2

    tmpf=`mktemp`
    bash -c "$* >> $tmpf 2>&1" # HERE
    retval=$?

    cat $tmpf >&2
    rm $tmpf

    echo >&2
    echo -e "\033[37m[${BASH_SOURCE[0]#*kissbash/}] \033[33mexpecting exit code "$expected_retval", got "$retval"\033[0m" >&2

    return $retval
}
